Add parent ids to cm response object
VorTECHsa/python-sdk pull request #250
Opened 2020-12-03 16:34 UTC by Selerski

2020-12-03 17:46 UTC, ChristianBorresen requested changes

2020-12-03 17:46 UTC, ChristianBorresen commented on vortexasdk/endpoints/endpoints.py
> +API_FQDN = "https://api-feat-parent-ids.public.kube.develop.vortexa.com"
We can't merge until this has changed.

2020-12-08 10:19 UTC, pep8speaks commented
Hello @Selerski! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`vortexasdk/api/cargo_movement.py`](https://github.com/VorTECHsa/python-sdk/blob/e501a3d21f82a30630e37753213b0af0fd665747/vortexasdk/api/cargo_movement.py):

> [Line 36:91](https://github.com/VorTECHsa/python-sdk/blob/e501a3d21f82a30630e37753213b0af0fd665747/vortexasdk/api/cargo_movement.py#L36): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2020-12-09 09:55 UTC, Selerski commented on vortexasdk/endpoints/endpoints.py
> +API_FQDN = "https://api-feat-parent-ids.public.kube.develop.vortexa.com"
I've restored the original api url

2020-12-09 10:45 UTC, KitBurgess commented on vortexasdk/api/cargo_movement.py
> +class ParentIds:
To be consistent with the rest of the ID classes naming conventions, shall we call this class `ParentID`. Also, this class refers to a single parent id, so it should be singular.

2020-12-09 10:56 UTC, KitBurgess approved these changes

2020-12-09 10:58 UTC, ChristianBorresen approved these changes

2020-12-09 11:03 UTC, merged

2020-12-29 16:53 UTC, KitBurgess commented
@all-contributors add @Selerski for code

2021-01-08 10:09 UTC, Selerski commented
@all-contributors add @dufia for code