Rnd 24 cargo move
VorTECHsa/python-sdk pull request #403
Opened 2022-11-25 11:18 UTC by jakubbuskiewicz

#### RELATED TICKETS

https://vortexa.atlassian.net/browse/RND-24

#### RELATED PRs

-

#### CHANGELOG

- added support for single cargo movement fetch (reference)

#### TESTS

- I QA'd changes locally
- test case was added

#### COMMENTS

- please take a look at changes in `vortexasdk/operations.py` as I had to change field where URL for Reference operation is stored (for fetching single cargo-movement reference we need to use different endpoint that is used for search operation)

2022-11-25 12:05 UTC, ministrudels commented on vortexasdk/operations.py
> +        data = default_client().get_reference(self._ref_resource, id)
nit: can we revert back to `_resource`. Class is already named Reference

2022-11-25 12:18 UTC, ministrudels commented on vortexasdk/endpoints/cargo_movements.py
> +        return super().reference(id)
`reference` refers to reference data, so I think this is a confusing API

2022-11-28 13:29 UTC, migueluzcategui approved these changes

2022-11-29 10:20 UTC, ChristianBorresen requested changes

2022-11-29 10:20 UTC, ChristianBorresen commented on vortexasdk/endpoints/cargo_movements.py
> +                unit: enter 'b' for barrels and 'b' for tonnes
I believe it should be b for barrels, t for tonnes, and cbm for cubic meters

2022-11-29 10:20 UTC, ChristianBorresen commented on vortexasdk/operations.py
> +                'unit': enter 'b' for barrels and 't' for tonnes
also cbm

2022-11-29 11:05 UTC, ChristianBorresen approved these changes
Please fix the two small typos

2022-11-29 11:05 UTC, ChristianBorresen commented on vortexasdk/operations.py
> +        An record matching the ID
"A record matching the ID"

2022-11-29 11:05 UTC, ChristianBorresen commented on vortexasdk/operations.py
> +        An record matching the ID
Same as above

2022-11-29 12:30 UTC, merged